
#include "MySPI.h"

//MOSI - PB15
//MISO - PB14
//SCK  - PB13
//NCS  - PC0
//LE	 - PA8

uint8_t SPI_SentByte_8(uint8_t byte)
{
	while((SPI2->SR & SPI_SR_BSY)==SPI_SR_BSY){}
	SPI2_DR8 = byte;
	while((SPI2->SR & SPI_SR_BSY)==SPI_SR_BSY){}
	return(SPI2_DR8);
}

void SPI_SentByte_16(uint16_t data)		//for matrix
{
			while((SPI2->SR & SPI_SR_BSY)==SPI_SR_BSY){}
			SPI2->DR = data;
			while((SPI2->SR & SPI_SR_BSY) == SPI_SR_BSY){}
}


void SPIconfig(void)
{
  RCC -> AHBENR |= RCC_AHBENR_GPIOAEN;
  RCC -> AHBENR |= RCC_AHBENR_GPIOBEN;
	RCC -> AHBENR |= RCC_AHBENR_GPIOCEN;
  RCC -> APB1ENR |= RCC_APB1ENR_SPI2EN;
	
	GPIOA->MODER &= ~(GPIO_MODER_MODER8); //LE GENERAL OUTPUT
	GPIOA->MODER |= (GPIO_MODER_MODER8_0);
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_8);//LE PushPull
  GPIOA->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR8);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR8);//LE PUPD
	
	GPIOB->MODER &= ~(GPIO_MODER_MODER13|GPIO_MODER_MODER15|GPIO_MODER_MODER14);//MOSI,SLC ALTERNATIVE FUNC
	GPIOB->MODER |= (GPIO_MODER_MODER13_1|GPIO_MODER_MODER15_1|GPIO_MODER_MODER14_1);
	GPIOB->OTYPER &= ~(GPIO_OTYPER_OT_13|GPIO_OTYPER_OT_15);//MOSI,SLC PushPull
	GPIOB->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR13|GPIO_OSPEEDER_OSPEEDR15);	
	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPDR13|GPIO_PUPDR_PUPDR15|GPIO_PUPDR_PUPDR14);//MOSI,SLC PUPD
	
	GPIOB->AFR[1] &= ~( GPIO_AFRH_AFRH5 | GPIO_AFRH_AFRH7);
	
	GPIOC->MODER &= ~(GPIO_MODER_MODER0);
	GPIOC->MODER |= (GPIO_MODER_MODER0_0);
	GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPDR0);

	SPI2->CR1 = SPI_CR1_SSM | SPI_CR1_SSI | SPI_CR1_BR | SPI_CR1_MSTR | SPI_CR1_CPOL | SPI_CR1_CPHA;
  //SPI2->CR2 = SPI_CR2_DS;//osc - data size
	//SPI2->CR2 = (0x07<<8)|(SPI_CR2_FRXTH);//gyr  /*!< FIFO reception Threshold */
  SPI2->CR1 |= SPI_CR1_SPE;									// spi peripheral enable
	
	while((SPI2->SR & SPI_SR_BSY)==SPI_SR_BSY){}
}

